{
	:title		"Reading"
	:page-index	-1
	:navbar?	false
}

:toc: macro

== My Reading List ==

This reading list is primarily focused on books in mathematics and occasionally other academic fields. It's ordered alphabetically (not automatically though, please contact me if there is a mistake) with no regard for quality. It may expand to a full list including fictional works or poetry at some point in the future. I also have not read everything in this list to completion, or even started reading, this is simply a list to keep track of what I have read and could still read. If you are curious about any of these books and they aren't available at a local public library, please contact me, I am happy to help you locate an affordable source.

> Culture shouldn't exist only for those who can afford it.
>
> __&#8212; Arsi "Hakita" Patala__

toc::[]

== Books

=== Abstract Algebra ===

* {empty}
+
--
.*A Course in Universal Algebra by Burris and Sankappanavar*
[%collapsible]
====
I am currently in the progress of reading this text, as it is the current focus of the algebra reading group which I host.

This book focuses on introductory universal algebra, which is the study of algebraic objects and theories.
====
--
* {empty}
+
--
.*A First Course in Noncommutative Rings by Lam*
[%collapsible]
====
I have read snippets of the book, as it was a recommended pre-reading for another book that I was looking at at some time.

This book focuses on the basics of noncommutative ring theory, which are essential for studying anything further in the subject.
====
--
* {empty}
+
--
.*Almost Free Modules - Set Theoretic Methods by Eklof and Mekler*
[%collapsible]
====
An intensive book, I am slowly working my way through reading this. I find the subjects within this book very interesting and am still deeply curious about the contents.

This book focuses on more advanced abstract algebra, in particular, the intersections with set theory. These relate to high-cardinality algebraic structures such as (as the name implies) almost free modules.
====
--
* {empty}
+
--
.*A Term of Commutative Algebra by Altman and Kleiman*
[%collapsible]
====
I have not yet read this book, but it was a possible selection for the algebra reading group which I host. I do plan to read this soon, as it seems quite interesting.

This book focuses on introductory commutative algebra, dealing with rings and modules and their place in commutative algebra.
====
--
* {empty}
+
--
.*Abelian Groups by Fuchs*
[%collapsible]
====
I am currently reading this book off and on; it is a tough read but I find the topics of great interest.

This book focuses on deeper topics related to abelian groups. In particular, lower level set-theory such as cardinalities are dealt with explicitly.
====
--
* {empty}
+
--
.*Abstract Algebra by Dummit and Foote*
[%collapsible]
====
I have read some of this book and I plan to read through its entirety at some point.

A staple of graduate courses in abstract algebra, this book gives a detailed introduction to many of the important topics in algebra.
====
--
* {empty}
+
--
.*Abstract Algebra by Judson*
[%collapsible]
====
I have read nearly the entirety of this book.

This book is a stellar introduction to basic topics in group, ring, and field theory, and its open source nature provides a great platform for new learners.
====
--
* {empty}
+
--
.*Abstract and Concrete Categories by Adamek, Herrlich, and Strecker*
[%collapsible]
====
I have not read much of this book, but it covers many topics I find interesting, so I expet to at least skim it at some point.

This book covers many important categorical constructions, and I have heard of it several times, so I imagine it does a good job of exposition.
====
--
* {empty}
+
--
.*Algebra by Hungerford*
[%collapsible]
====
I have skimmed some pages of this book; it was a possible selection for the algebra reading group which I host.

I originally looked at this book for a suitable introduction to commutative algebra and possibly basic algebraic geometry, which is minorly covered in one of the later chapters.
====
--
* {empty}
+
--
.*Algebra: An Approach via Module Theory by Adkins and Weintraub*
[%collapsible]
====
I have skimmed some pages of this book; it was a possible selection for the algebra reading group which I host.

I saw this book as a way to dive deeper into some concepts in module theory if people were so inclined, but this book was not chosen, and as such I cannot say much about it.
====
--
* {empty}
+
--
.*Algebra: Chapter 0 by Aluffi*
[%collapsible]
====
I picked this book up over my winter break in 2025 to review my algebra before I took a class in module theory. I have read the first 7 or so chapters, and I plan to finish the book at some point.

This book has stellar exposition, and I greatly recommend it to anyone aiming to learn algebra. It starts from the very top of group theory and works through each subject at a consistent pace. It contains brief categorical perspectives which allow the reader to explore deeper on their own.
====
--
* {empty}
+
--
.*Categorical Logic and Type Theory by Jacobs*
[%collapsible]
====
I have not read much of this book apart from the introduction, but I would like to learn more type theory at some point, and this book certainly piques my interest in that regard.

A good foundation of category theory and similar mathematical topics is expected as a prerequisite, but as such this book is able to move quite quickly into advanced topics.
====
--
* {empty}
+
--
.*Categorical Models of Constructive Logic by Streicher*
[%collapsible]
====
I would love to read this text, but much of the notation is still unknown to me. I plan to come back to this at some point soon.

This text is very short and covers some topics that would be great to learn such as hyperdoctrines, but it expects prerequisites that I don't yet have, so I can't speak on it yet.
====
--
* {empty}
+
--
.*Categories, Allegories by Freyd and Scedrov*
[%collapsible]
====
I have read the beginning of this book and it was one of the possibile candidates to read in the algebra reading group that I run, but I have not read too significant of an amount.

This text uses several pieces of non-standard notation that I am not a fan of, although they might pose some benefit that I am not aware of. Apart from this, it covers many important categorical concepts in great detail.
====
--
* {empty}
+
--
.*Categories for the Working Mathematician by MacLane*
[%collapsible]
====
A classic piece of literature in category theory, I have read pieces of this book but not the entirety yet, but I do expect this to change eventually.

This book contains many of the most foundational results in category theory and how they relate to mathematicians who aren't working on abstract category theory, hence the name 'for the working mathematician'.
====
--
* {empty}
+
--
.*Complexity of Infinite Domain Constraint Satisfaction by Bodirsky*
[%collapsible]
====
I found this book while I was unsure of what to read, but I have not read it yet. I plan to read this, as it seems to cover many greatly interesting topics.

I cannot speak much about the book, but it does talk on satisfiability problems, model theory, universal algebra, and Ramsey theory, among other topics.
====
--
* {empty}
+
--
.*Elements of Set Theory by Enderton*
[%collapsible]
====
I found this book while trying to re-learn set theory, in particular, trying to have a better foundation of ordinals and cardinals. I have not read the entire book, but the snippets I have read seem good.

This book covers much of foundational set theory and, from what I have read, seems like a very good introduction to the topic. It also deals slightly with more advanced topics like cofinality, which were good from my experience.
====
--
* {empty}
+
--
.*Foundations of Module and Ring Theory by Wisbauer*
[%collapsible]
====
I have not yet read the majority of this book, but it was a possible selection for the algebra reading group which I host. I do plan to read more of this book at some point, as it seems to cover much of module theory in great detail.

This book seems to serve as a great introduction to ring and module theory and dives into many more advanced topics, including categories. This does use the slightly non-standard notation of functions being applied on the right, although it leads to some conditions being nicer.
====
--
* {empty}
+
--
.*Fuchsian Groups by Katok*
[%collapsible]
====
I am in the process of reading this book, as I am currently auditing a course (of the same name) which has this book as the designated reading.

This book seems to treat the topics inside with a great deal of detail, which, as someone who is unfamiliar to some of the concepts, has worked well for me.
====
--
* {empty}
+
--
.*Intro to Higher Order Categorical Logic by Lambek and Scott*
[%collapsible]
====
I have not read this book yet, but I plan to, and at one point it was the main book to read for a reading group that was never started.

This book has a very quick introduction to category theory but seems to cover many very important concepts in categorical logic.
====
--
* {empty}
+
--
.*Introduction to Modern Algebra by Joyce*
[%collapsible]
====
I have not read this book, but it was shown to me by a friend, and it seems to take an unusual enough approach that it is worth reading eventually.

This book seems to cover most basic algebra concepts that should be found in any standard introductory course in modern algebra, but it covers them backwards from the usual, starting at fields then working backwards to rings and groups.
====
--
* {empty}
+
--
.*Lattices and Ordered Algebraic Structures by Blyth*
[%collapsible]
====
I have read a very small portion of this book, but I plan to read significantly more, as the topic interests me greatly.

I know much less than I would like to in the advanced portions of lattice theory, and so I cannot speak to the details of the book, but the exposition that I have read so far has been well done.
====
--
* {empty}
+
--
.*Lie Groups, Lie Algebras, and Representations by Hall*
[%collapsible]
====
I have not yet read this book, but it was a possible selection for the algebra reading group which I host.

This book seems to do a good job of covering topics like Lie Groups and Lie Algebras without delving too far into the analysis side of things, which is the perspective I tend to look for.
====
--
* {empty}
+
--
.*Model Theory: An Introduction by Marker*
[%collapsible]
====
I have only read the first couple chapters of this book, but I may return to it at some point.

Model theory is often covered in other books at a (presumably) fairly shallow level, and so having a book dedicated to the nuances to in-depth model theory seems good. From what I remember, the exposition was good, and I enjoyed what I did read.
====
--
* {empty}
+
--
.*Notes on Set Theory by Moschovakis*
[%collapsible]
====
I have read a very small portion of these notes, although they seem to be a good place to learn things that I have been meaning to, so I will likely return to them at some point.

These notes are very dense and don't follow the usual stuctures of a textbook, but they do serve as a walk through much more advanced set theory than most books include.
====
--
* {empty}
+
--
.*Post Modern Algebra by Smith and Romanowska*
[%collapsible]
====
I have begun reading this book, and I have also read a portion regarding quasigroups, as this was a text that I found when I first approached the subject.

This book seems to be a good, distinct perspective on learning modern (or post modern) algebra and covers topics such as semigroups, monoids, and quasigroups quite deeply. This seems less common, and so I welcome the perspective, especially as quasigroups have been very interesting to work with so far.
====
--
* {empty}
+
--
.*Representation Theory: A Categorical Approach by Grabowski*
[%collapsible]
====
I have read snippets of this book, as it was recommended to me by a friend but I already know much of the content. I would love to read more of this at some point.

This book is well written from what I have read so far, but that it not much.
====
--
* {empty}
+
--
.*Set Theory by Jech*
[%collapsible]
====
I have jumped around in this book, and I primarily got this book to read more on cofinality. I plan to read more in the near future.

From what I have read so far, this book does a great job of treating set theory with the precision it needs, which has been helpful for learning more advanced topics.
====
--
* {empty}
+
--
.*Sheaves in Geometry and Logic by MacLane and Moerdijk*
[%collapsible]
====
I have not read very much of this book, but I plan to continue soon, as it covers many topics that I am greatly interested in.

From what I have read, this book seems to have decent exposition and I am interested to see how it treats more advanced topics.
====
--
* {empty}
+
--
.*Stone Spaces by Johnstone*
[%collapsible]
====
I have read the first couple chapters of this book, and I plan to continue at some point, but it is a difficult read.

An advanced book that is a tricky read, but from what I have read so far it has done a good job of explaining core concepts.
====
--
* {empty}
+
--
.*Topoi, the Categorical Analysis of Logic by Goldblatt*
[%collapsible]
====
I have read most of this book, but was unable to finish the final couple chapters due to time constraints.

This book does a stellar job of teaching internal category theory and the internal logic of topoi, despite not talking about (usually very important) topics such as functors and adjunctions for a significant portion of the book.
====
--
* {empty}
+
--
.*Toposes, Triples, and Theories by Barr and Wells*
[%collapsible]
====
I have independently found this book several times, and it was a possible candidate for the algebra reading group that I run. I have not yet read any significant portion of the book.

This book seems to do a detailed but dense job of discussing many of the introductory topics concerning categorical logic, and dives into more advanced concepts in the later half.
====
--

=== Algebraic Geometry ===

* {empty}
+
--
.*Algebraic Geometry by Hartshorne*
[%collapsible]
====
I have tried reading this book several times and have gotten further each time. No doubt I could read this book now, but I have not found the time to do so.

This book is a tough read but is widely regarded as a great way to learn algebraic geometry if you can get through it.
====
--
* {empty}
+
--
.*Beginning in Algebraic Geometry by Clader and Ross*
[%collapsible]
====
I don't remember when I found this book, but it seems lke a suitable introduction to algebraic geometry. I may read through it at some point.

This book seems to cover all the topics crucial to algebraic geometry, but I do not know enough of the subject to make further comments.
====
--
* {empty}
+
--
.*Introduction to Algebraic Geometry by Hassett*
[%collapsible]
====
I got this book as a possible choice for the algebra reading group that I run, but I would love to read through it at some point.

This book seems like a great introduction to algebraic geometry, and includes some topics that I have wanted to learn for some time such as Grobner bases.
====
--

=== Analysis ===

* {empty}
+
--
.*Complex Analysis by Stein and Shakarchi*
[%collapsible]
====
I am currently in a course using this book as the primary text, so I am in the process of reading it.

This book's expositions has been very well done from what I have read so far, but that is not very far.
====
--
* {empty}
+
--
.*Function Theory of One Complex Variable by Greene and Krantz*
[%collapsible]
====
This book was a suggested supplement to a complex analysis course, but I have not yet read any of it.

I have not actually looked at this book yet, so I cannot speak to how well it details its subject.
====
--
* {empty}
+
--
.*Measure, Integration, and Real Analysis by Axler*
[%collapsible]
====
I have read the first three (or so) chapters of this book, and it would be good for me to read more of it at some point.

This book does an okay job at exposition, but sometimes is missing details that could be important.
====
--
* {empty}
+
--
.*Real Analysis by Carothers*
[%collapsible]
====
This was the required text for a course in analysis that I took, and without that course I would not have read this book.

This book does a generally alright job at handling analysis, but has mistakes in some crucial places like the Arzela-Ascoli theorem.
====
--
* {empty}
+
--
.*Real Analysis by Stein and Shakarchi*
[%collapsible]
====
I have not read any significant amount of this book, and I do not know why I own it. I may still come back and read it at some point.

I cannot speak much to the exposition nor the content of this book.
====
--
* {empty}
+
--
.*Set Theory and Metric Spaces by Kaplansky*
[%collapsible]
====
I am not entirely sure when I obtained this book, and it is short enough that from a brief skim I seem to already know much of the subjects covered.

This book seems to cover topics which serve as a good introduction to basic set theory and metric spaces, including an introduction to topological spaces at the end.
====
--
* {empty}
+
--
.*Understanding Analysis by Abbott*
[%collapsible]
====
I used this book for my undergraduate advanced calculus courses, although we did not cover all of the additional topics at the end of the book.

I enjoyed the exposition in this book, and it served as a great introduction to the basics of analysis such as $\varepsilon$-$\delta$ proofs.
====
--
* {empty}
+
--
.*Vector Calculus, Linear Algebra, and Differential Forms by Hubbard and Hubbard*
[%collapsible]
====
This book was the text for a class on multivariable advanced calculus that I took, but the class did not follow the book particularly closely, and as such I have not read this book.

I believe I have heard good things about this book, although I cannot speak to it myself.
====
--

=== Linear Algebra ===

* {empty}
+
--
.*Linear Algebra by Friedberg, Insel, and Spence*
[%collapsible]
====
I do not remember why I specifically own this book, although I do know that this book is very well known, and I would expect it to have good exposition.

This book primarily focuses on undergraduate linear algebra, covering the basics as well as a more advanced course with the discussion of topics like SVD, bilinear forms, and canonical forms.
====
--
* {empty}
+
--
.*Linear Algebra Done Right by Axler*
[%collapsible]
====
I have this both because of its fame, and since a reading group I participated in used it briefly. I have sparsely read the intermediate chapters and closely read the final chapter "Multilinear Algebra and Determinants".

This book creates polarizing opinions, and I do not agree with the ordering of this book. I believe that determinants should be learned, at least in the most basic form, long before bilinear forms and canonical forms. I also have long had a distaste for Axler's exposition. I respect that this book is well known and should often be mentioned, but I would highly recommend using a different book to learn linear algebra.
====
--
* {empty}
+
--
.*Linear Algebra Done Wrong by Treil*
[%collapsible]
====
My first proof-based linear algebra class used this book, and although the class went a bit slow, I have now read through most of this book.

I enjoyed the ordering of the material in this book, which is evidently the wrong way. I would highly recommend this as a first book for many topics in linear algebra.
====
--

=== Topology ===

* {empty}
+
--
.*Algebraic Topology by Hatcher*
[%collapsible]
====
This book served as a secondary reading for my first class in algebraic topology, supplementing Munkres' Topology. As such, I have read the first chapter thoroughly, but have not read further into the chapters are homology and cohomology.

This book uses certain conventions that I don't agree with, and many proofs are hand-waved away. Despite this, it still has good exposition and many theorems are stated very nicely, particularly the Van Kampen theorem.
====
--
* {empty}
+
--
.*General Topology by Willard*
[%collapsible]
====
I got this book for its discussion of nets and filters, as I was intrigued at their use in general topology. I have not read very much of this book past those sections and the few surrounding them.

The sections on nets and filters are well written and provide a lot of the useful intuition around the subject, but are by no means perfect. They are useful as a supplement to a text like Munkres' Topology, which does not thoroughly cover nets or filters.
====
--
* {empty}
+
--
.*Topology by Munkres*
[%collapsible]
====
This was my primary text for my first class in general topology and my first class in algebraic topology, and so I have read almost the entirety of the book, with a few exceptions throughout.

Munkres' Topology is a spectacular book for a first course in topology, either at the late undergraduate or early graduate level. The exposition is well done and the majority of the theorems are well stated.
====
--

=== Probability ===

* {empty}
+
--
.*An Introduction to Measure and Probability by Taylor*
[%collapsible]
====
This is the book for one of my courses on probability theory, but I have only read through (roughly) the first chapter thus far.

This book focuses on a rigorous development of probability theory using measure theory, giving a more rigorous mathematical foundation than many other books.
====
--
* {empty}
+
--
.*An Introduction to Statistical Learning with Applications in R by James, Witten, Hastie, and Tibshirani*
[%collapsible]
====
This is supplemental reading for one of my courses on statistical signal processing, but as it was not required I have not read this book.

This book covers topics such as estimation, classification, and unsupervised learning, among many others.
====
--
* {empty}
+
--
.*Introduction to Probability by Bertsekas and Tsitsiklis*
[%collapsible]
====
I got this book for an engineering probability course that I took, but I never ended up reading it. I plan to learn more probability, so I may return to this book.

As I haven't read any of this book, I can't speak to its content further than it being an introduction to very basic probability.
====
--

=== Theoretical Computer Science ===

* {empty}
+
--
.*Formal Languages and Automata by Linz Rodger*
[%collapsible]
====
The book for my first course in theory of computation, and I have read just over half of it. I may read more eventually, it is unsure.

Of what I read, this book had well done exposition, although it was tailored to the computer scientist. Some of the more intensive proofs were left out, but nothing had a significant reliance on anything left unproven. I would highly recommend this book as an introduction to finite automata and turing machines.
====
--
* {empty}
+
--
.*Programming Language Fundamentals by Martin Erwig*
[%collapsible]
====
This book was written by a professor at Oregon State University, and so in preparation for taking his class, I read this entire book over the summer of 2025.

This book was my first exposure to this subject, so I feel like I have difficulty placing how good it is. I definitely learned many important concepts from it, and I think it covers a good breadth, even delving into type theory for a short time.
====
--

=== Computer Architecture ===

* {empty}
+
--
.*Computer Architecture: A Quantitative Approach by Hennesy and Patterson*
[%collapsible]
====
An absolute behemoth of a book, I surely have not read all of it. I have read a lot though, and many of the appendices, where much of the information lies.

This book covers the topic of computer architecture in a very thorough fashion, with examples and history abound. Much of the content lies in the appendices, so do not miss them when you read this.
====
--
* {empty}
+
--
.*Computer Organization and Design by Hennesy and Patterson*
[%collapsible]
====
I have not read as much of this book as the more advanced version by the same authors, but I have still read a good amount of the main content of this book.

This book serves as a better introduction to computer architecture than its cousin, but covers fewer advanced topics. I would definitely recommend reading this book first if you are unfamiliar with the topics.
====
--
* {empty}
+
--
.*Digital Design and Computer Architecture by Harris and Harris*
[%collapsible]
====
I got this boook for my first class in digital logic design, and it was well worth it. I read through much of the book during that time, and although I have not read much since then, it covers many more advanced topics.

Slightly lower level than the other architecture books that I own, this book focuses on building up a computer from very basic transistors and logic gates. It gets into more advanced topics that I have not read as much about, but does not delve as deep into higher performance architectures as the books from Hennesy and Patterson.
====
--

=== Distributed Systems ===

* {empty}
+
--
.*Distributed Systems by Coulouris, Dollimore, Kindberg, and Blair*
[%collapsible]
====
I got this book as a recommendation from a professor teaching a course on distributed systems

This book focuses on the fundamentals of operating systems very thoroughly, and I've heard very good things about its exposition, although I have not read very much of it myself.
====
--
* {empty}
+
--
.*Operating Systems: Three Easy Pieces by Arpaci-Dusseau and Arpaci-Dusseau*
[%collapsible]
====
I got this book as a text for a course, but did not end up reading very much of it. It does seem like a good text, and so I might return to it in the future.

This book focuses on the fundamentals of operating systems very thoroughly, and I've heard very good things about its exposition, although I have not read very much of it myself.
====
--

=== Operating Systems ===

* {empty}
+
--
.*Operating Systems: Three Easy Pieces by Arpaci-Dusseau and Arpaci-Dusseau*
[%collapsible]
====
I got this book as a text for a course, but did not end up reading very much of it. It does seem like a good text, and so I might return to it in the future.

This book focuses on the fundamentals of operating systems very thoroughly, and I've heard very good things about its exposition, although I have not read very much of it myself.
====
--
* {empty}
+
--
.*xv6: A Simple, Unix-like Teaching Operating System by Cox, Kaashoek, and Morris*
[%collapsible]
====
I got this text for a course where we worked on a version of the xv6 operating system, so I have read snippets that were relevant at the time but no more.

This book was good for the use of a course focusing on developing the xv6 operating system, but I did not read it contiguously, so I don't feel confident speaking to its merits otherwise.
====
--

=== Quantum Computing ===

* {empty}
+
--
.*Mathematics of Quantum Computing by Scherer*
[%collapsible]
====
I have not yet read this, but it was a gift from a friend and I intend to read at least parts of it eventually.
====
--
* {empty}
+
--
.*Quantum Computation and Quantum Information by Nielsen and Chuang*
[%collapsible]
====
I have not yet read this, but it was a gift from a friend and I intend to read at least parts of it eventually.
====
--
* {empty}
+
--
.*Quantum Computer Science by Mermin*
[%collapsible]
====
I have not yet read this, but it was a gift from a friend and I intend to read at least parts of it eventually.
====
--
* {empty}
+
--
.*Quantum Computing: A Gentle Introduction by Rieffel and Polak*
[%collapsible]
====
I have not yet read this, but it was a gift from a friend and I intend to read at least parts of it eventually.
====
--

=== Circuit Design ===

* {empty}
+
--
.*Circuit Analysis and Design by Ulaby, Maharbiz, and Furse*
[%collapsible]
====
I got this book for one of my first courses in circuit design, but I only ever read snippets. I know most of the material now, so it is unlikely I will go back to this book.

This covers DC and AC circuit analysis, including technqiues like Laplace and Fourier transforms. Presumably it is a good introduction to the topics.
====
--
* {empty}
+
--
.*Microelectronic Circuits by Sedra and Smith*
[%collapsible]
====
A book for a more advanced class I took on circuit design, so (as I have a tendency to do with electrical engineering) I have barely read this.

I have heard great reviews from trusted about this book, so I would highly recommend it if you are interested in the topics inside.
====
--

== Papers ==

=== Representation Theory ===

* {empty}
+
--
.*Combinatorics and the Schur Algebra by Green*
[%collapsible]
====
A paper I was given by a mentor for a direct reading program. We quickly switched to 'Schur-Weyl Duality' by Stevens, which was more aligned to our goals.
====
--
* {empty}
+
--
.*Schur-Weyl Duality by Stevens*
[%collapsible]
====
A paper I am currently reading for a directed reading program I am in, it introduces you to representations of fgroups, and some important results about representations of finite groups and $S_n$ in particular. I have not yet finished reading this paper.
====
--

=== High Performance Computing ===

* {empty}
+
--
.*Buffets: An Efficient and Composable Storage Idiom for Explicit Decoupled Data Orchestration by Pellauer et al.*
[%collapsible]
====
One of a couple papers that a professor gave to me for possible research. It covers an alternate storage method that allows for better and faster control called a buffet. It serves as a structure somewhere in between a scratchpad and a cache, helping with fast and precise memory accesses.
====
--
* {empty}
+
--
.*Isolating Functions at the Hardware Limit with Virtines by Wanninger et al.*
[%collapsible]
====
One of a couple papers that a professor gave to me for possible research. It talks about using 'virtines', named to be virtual coroutines, a way of isolating certain function execution using very small but fast virtual machines.
====
--
* {empty}
+
--
.*PULSE: Accelerating Distributed Pointer-Traversals on Disaggregated Memory (Extended Version) by Tang et al.*
[%collapsible]
====
One of a couple papers that a professor gave to me for possible research. These researchers constructed a hardware accelerator to do near-memory pointer traversals. It is meant to be easily integrable into current systems, allowing modern data structures with lots of pointer traversals to operate much faster.
====
--



