{
	:title		"Professional"
	:page-index	0
	:navbar?	true
}

== My Career ==

I am currently spending four years at Oregon State University to complete three majors: mathematics, computer science, and electrical and computer engineering. I plan to to continue studying mathematics at a PhD program after I complete my undergrad in the spring of 2027. I hope to one day be a professor of mathematics, doing both research and teaching students.

== Past Experience ==

Most recently, I have been working as a lab TA for the first course on electronic devices such as diodes and transistors. My first term as a TA for this course was the first term the course has had a lab in nearly 20 years, and as such I have helped to develop and improve much of the content of the labs within the course to match the modern curriculum better. The lab primarily has the students building the components to a power supply such as a voltage rectifier, voltage regulator, and current regulator, using fundamental techniques such as feedback loops and Darlington pairs.

I am also currently a learning assistant for integral calculus, and have also helped with vector calculus in the past. The learning assistant program at OSU had me attend a pedagogy course to help me become a better teacher, particularly in active learning environments. As a learning assistant, I primarily help students in-class with worksheets done in a reversed classroom, meaning I get meaningful time to guide students to figuring out problems themselves.

In high school, I worked as a tech assistant, meaning I helped repair laptops that were brought in and format new laptops. This gave me invaluable technological skills that have allowed me to be consistently up-to-date with techonology and always able to troubleshoot and fix problems on the fly.

Outside of academia, I have also been a resident assistant since my second year of undergrad (fall 2024), where I help new students living in residence halls get acquianted with our campus and find a sense of community. This is a particularly rewarding job as I get to help so many young adults find their different pathways through life.

== Research ==

In the fall, and over the course of the 2026-27 school year, I will be completing both my Honors thesis with Prof. Jon Kujawa in a (currently undecided) field of abstract algebra as well as my capstone project, which is currently planned to be research expanding upon virtines, a concept first explored in link:https://arxiv.org/pdf/2104.11324[this] 2021 paper. I have high expectations for my Honors thesis, as I am deeply passionate about topics surrounding module theory, and I am currently doing a summer reading with Prof. Kujawa in the representation theory of partition algebras. I am similarly interested in working with virtines, in particular the possibility of doing semantic evaluation of functions and creating a modular operating system that serves as a minimal execution environment for said function within a virtine.

I am currently at an REU at Iowa State University studying temporal logic under Prof. Kristin Yvonne Rozier and Prof. Phillip Jones. My group has taken up the task of translating the semantics for spatial robustness from signal temporal logic (STL) into mission-time linear temporal logic (MLTL). This involves defining signals and signal maps, robustness, and robust intervals with a version of finite interval-based linear temporal logic which can specify to MLTL. This has led to disproving a highly-cited paper's foundational lemma, and instead providing sufficient conditions for which it holds. We have also made algorithms for calculating robust intervals in real-time and proven their correctness for online stream-based monitors. We are in the process of implementing the first version of these algorithms into R2U2, an MLTL monitor that previously had no robustness metrics. We will present the research we have so far at Iowa State's summer poster session and at the MAA Math Fest in Boston. We hope to continue doing this research and publish a paper with our findings soon.

In my third year of my undergrad (2025-26), I participated in the pilot program for the OSU Math Department's directed reading program. Alongside Kellen Houchin, I did various readings directed by Addison Day, a student of Prof. Jon Kujawa. We primarily read about the representations of finite groups, and the classification of the representations of the symmetric groups using partitions and Young tableau. We also read about representations of Lie algebras and Schur-Weyl duality. I gave a presentation about the characters of representations, which worked from the definition of a representation up to characters tables, mainly providing motivations instead of proofs. Here is the alink:../../files/DRP_Presentation.pdf[pdf of the presentation].

In my second year of my undergrad (2024-25), I worked with Prof. Nick Marshall through the URSA program to do basic research in stochastic linear algebra. In particular, I examined the randomized Kaczmarz algorithm and variations upon it. I developed my own version to allow it to more effectively counteract highly corrupted datasets, and gave a poster presentation on this at OSU's spring poster symposium. Here is the link:../../files/URSA_Poster.pdf[pdf of my poster].

== Resources ==

A PDF copy of my resume is linked below, which has much of the information above in more detail, along with several of my projects and my coursework. The best way to get in contact with me is usually by email, but my LinkedIn and GitHub are also linked below.

*CV:* link:../../files/CV.pdf[Get CV]

*Email:* carewj@oregonstate.edu

*LinkedIn:* link:https://www.linkedin.com/in/jonas-carew[linkedin.com/in/jonas-carew]

*GitHub:* link:https://github.com/Jonas-Carew[github.com/Jonas-Carew]



